name: onnx_flutter
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/ArishSultan/onnx_flutter.git

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  ffi: ^2.0.1
  image: ^3.2.2

dev_dependencies:
  ffigen: ^7.2.2
  lints: ^2.0.0
  test: ^1.21.0

ffigen:
  output: 'lib/generated_bindings.dart'
  headers:
    entry-points:
      - '../onnx_wrapper/library.h'
